### ISSUE TITLE
Team formation

### ISSUE THREAD

**Issue by raelga** [kcd-es/spain-2021#1]
## What

We'll need to fill the following core roles + shadows to get the ball rolling. The current list of role responsibilities is just a suggestion based on the last meeting.  Each team will decide on sub-team roles and responsibilities (ie - marketing lead will determine if a writer is needed) based on the direction of the event. 

This is our first event, so all Lead roles are open for self-nomination and will be decided in the next public meeting. Shadows for the roles do not need to have event experience but should be ok with taking a Lead role within the next 12 months of events.

## How

The Guide from the Kubernetes Community Days website:

https://kubernetescommunitydays.org/organizing/

The checklist:

[Kubernetes Community Days Conference Action Items and Assignments
](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=0)

### Event coordination

- Project management
- CNCF interactions
- SIG-Contribex interactions
- Sponsorship (if applies)

### Content

- Define event tracks and schedule
- Talk introduction / moderation
- Call for proposals ingestion / Speakers

### Marketing

- Website
- Social media / Community management
- Call for proposals form
- Swag (if applies)

### Multimedia

- Bevy platform setup
- Recordings edit / publication
- Technical support

## Team

| Role               | Lead            | Shadow          | Notes |
| ------------------ | --------------- | --------------- | ----- |
| Event coordination |  @raelga    |      @javierprovecho  @agonzalezro         |       |
| Content            | @angelbarrera92 |     @agonzalezro  <br> @javierprovecho    <br> @jorgermp       |       |
| Marketing          |         @raelga        |  @andreugallofre <br> @raelga  <br> @rberrelleza              |       |
| Multimedia         |          @javierprovecho     | @andreugallofre <br> @angelbarrera92<br> |       |

**Comment by angelbarrera92** [comment]
Ciao @raelga, 

If I may propose myself to a couple of roles, I can be "lead" at Content and "shadow" on Multimedia.


Thanks!

**Comment by agonzalezro** [comment]
Hi! Shadow on Content & happy to shadow in any other if needed. I could lead event coordination but I don't fully know how deep is the work needed there (maybe we would need more than one lead on that one?).

**Comment by raelga** [comment]
@agonzalezro is just a proposal to discuss over the next meeting tomorrow and formalice the teams. Some roles, like the event coordination or content are quite more demanding than others, so have a lot of sense to split them smaller roles and have a lead/owner for each one.

Thanks @angelbarrera92, added to the table!

I'm going to apply as lead for `event coordination` and shadow for the `marketing` team.

**Comment by andreugallofre** [comment]
Hello! As discused with @raelga I don't have enough time to take a leading role as I'm part of the organization of HackUPC, an online hackathon that will take place on mid may, but I can shadow both Marketing and Multimedia :)

**Comment by javierprovecho** [comment]
I can lead multimedia and shadow content and/or event coordination.

**Comment by raelga** [comment]
I will add myself as Marketing lead, as there are no more candidates at this point :p

**Comment by jorgermp** [comment]
Add me to Content Shadow
